# GitHub Dependabot Configuration for Flask Ecosystem Migration
# Automated dependency updates and security vulnerability monitoring for Python Flask application
# Migration from Node.js/Express.js to Python 3.13.3/Flask 3.1.1 per Technical Specification Section 0.1.1

version: 2
updates:
  # Python package ecosystem monitoring with pip package manager
  # Monitors Flask ecosystem components per Section 3.2 and Section 8.4.4
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Weekly monitoring schedule for security-focused priority per Section 8.4.4
      # Balances security maintenance with production stability requirements
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    
    # Security vulnerability detection and automated pull request generation per Section 8.4.1
    # Enhanced monitoring for Flask ecosystem critical components
    open-pull-requests-limit: 10
    
    # Pull request configuration for CI/CD pipeline integration per Section 8.4.4
    pull-request-branch-name:
      separator: "-"
    
    # Automated commit messages for clear dependency tracking
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Labels for automated CI/CD workflow integration and security priority classification
    labels:
      - "dependencies"
      - "security"
      - "flask-ecosystem"
      - "python-3.13.3"
      - "automated-pr"
    
    # Reviewers and assignees for security-critical updates
    reviewers:
      - "devops-team"
      - "security-team"
    
    # Target specific Flask ecosystem components for enhanced monitoring per Section 3.2
    # Prioritizes security updates for core Flask dependencies
    allow:
      # Core Flask framework and dependencies (Section 3.2.1)
      - dependency-name: "flask"
        dependency-type: "direct"
      - dependency-name: "werkzeug"
        dependency-type: "direct"
      - dependency-name: "itsdangerous"
        dependency-type: "direct"
      - dependency-name: "jinja2"
        dependency-type: "direct"
      - dependency-name: "click"
        dependency-type: "direct"
      - dependency-name: "blinker"
        dependency-type: "direct"
      
      # Database integration components (Section 3.2.2)
      - dependency-name: "flask-sqlalchemy"
        dependency-type: "direct"
      - dependency-name: "flask-migrate"
        dependency-type: "direct"
      - dependency-name: "sqlalchemy"
        dependency-type: "direct"
      - dependency-name: "alembic"
        dependency-type: "direct"
      
      # Authentication and security libraries per Section 6.4
      - dependency-name: "flask-login"
        dependency-type: "direct"
      - dependency-name: "flask-jwt-extended"
        dependency-type: "direct"
      - dependency-name: "flask-principal"
        dependency-type: "direct"
      - dependency-name: "flask-security"
        dependency-type: "direct"
      - dependency-name: "flask-wtf"
        dependency-type: "direct"
      - dependency-name: "wtforms"
        dependency-type: "direct"
      
      # Production deployment dependencies per Section 8.1.1
      - dependency-name: "gunicorn"
        dependency-type: "direct"
      - dependency-name: "psycopg2-binary"
        dependency-type: "direct"
      - dependency-name: "psycopg2"
        dependency-type: "direct"
      
      # AWS SDK and cloud infrastructure dependencies per Section 8.2
      - dependency-name: "boto3"
        dependency-type: "direct"
      - dependency-name: "botocore"
        dependency-type: "direct"
      
      # External service integration per Section 6.4.1
      - dependency-name: "auth0-python"
        dependency-type: "direct"
      - dependency-name: "requests"
        dependency-type: "direct"
      - dependency-name: "urllib3"
        dependency-type: "direct"
      
      # Monitoring and observability dependencies per Section 6.4.6.1
      - dependency-name: "prometheus-client"
        dependency-type: "direct"
      - dependency-name: "structlog"
        dependency-type: "direct"
      - dependency-name: "python-json-logger"
        dependency-type: "direct"
      
      # Security scanning and validation tools per Section 8.4.1
      - dependency-name: "safety"
        dependency-type: "direct"
      - dependency-name: "bandit"
        dependency-type: "direct"
      - dependency-name: "cryptography"
        dependency-type: "direct"
      - dependency-name: "certifi"
        dependency-type: "direct"
      
      # Testing framework dependencies for security validation per Section 6.4.5.2
      - dependency-name: "pytest"
        dependency-type: "direct"
      - dependency-name: "pytest-flask"
        dependency-type: "direct"
      - dependency-name: "pytest-cov"
        dependency-type: "direct"
      
      # Data processing and ML dependencies for anomaly detection per Section 6.4.6.1
      - dependency-name: "numpy"
        dependency-type: "direct"
      - dependency-name: "scikit-learn"
        dependency-type: "direct"
      - dependency-name: "pandas"
        dependency-type: "direct"
      
      # All other security updates for transitive dependencies
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
    
    # Ignore specific updates that may cause breaking changes during migration
    # Focused on maintaining Python 3.13.3 compatibility per Section 3.1
    ignore:
      # Pin major Flask version during migration for stability
      - dependency-name: "flask"
        update-type: "version-update:semver-major"
      
      # Pin SQLAlchemy major versions to prevent migration conflicts
      - dependency-name: "sqlalchemy"
        update-type: "version-update:semver-major"
      
      # Ignore Python version updates outside of 3.13.x range
      - dependency-name: "python"
        versions: ["< 3.13.0", ">= 3.14.0"]
    
    # Milestone assignment for tracking dependency updates in sprint planning
    milestone: "dependency-maintenance"
    
    # Target branch for pull requests (typically main or develop)
    target-branch: "main"

  # Docker ecosystem monitoring for base image security updates per Section 8.3
  # Monitors python:3.13.3-slim base image and container dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      # Weekly monitoring for container security updates per Section 8.3.1
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    
    # Container security focus for base image updates
    open-pull-requests-limit: 5
    
    # Labels for container security tracking
    labels:
      - "dependencies"
      - "docker"
      - "security"
      - "python-3.13.3-slim"
      - "container-security"
    
    # Reviewers for container security updates
    reviewers:
      - "devops-team"
      - "security-team"
    
    # Commit message configuration for container updates
    commit-message:
      prefix: "docker"
      include: "scope"
    
    # Allow only security updates for Docker base images
    allow:
      - dependency-type: "direct"
        update-type: "security"
    
    # Target branch alignment with application updates
    target-branch: "main"

  # GitHub Actions ecosystem monitoring for CI/CD security per Section 8.4.4
  # Monitors GitHub Actions workflows and security scanning tools
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Monthly monitoring for GitHub Actions security updates
      interval: "monthly"
      day: "first"
      time: "11:00"
      timezone: "UTC"
    
    # Limit GitHub Actions PRs to maintain workflow stability
    open-pull-requests-limit: 3
    
    # Labels for CI/CD security tracking
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "security"
      - "automation"
    
    # Reviewers for CI/CD security updates
    reviewers:
      - "devops-team"
    
    # Commit message configuration for GitHub Actions updates
    commit-message:
      prefix: "ci"
      include: "scope"
    
    # Allow only security updates and minor version updates for actions
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
    
    # Target branch alignment with application updates
    target-branch: "main"